version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-latest" # <-- The actual correct way to trigger Conda on RTD

sphinx:
  configuration: docs/conf.py

conda:
  environment: docs/requirements.yaml
